language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install codecov
  - bash create_dev_environment.sh

script:
  - pytest
