version: '3'
services:
  mlflow:
    env_file: .env
    build: .
    ports:
    - "5000:5000"
    - "8000:8000"
    links:
    - mysql
    depends_on:
    - "mysql"
    volumes:
    - ./:/app

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlflow
    ports:
    - "3306:3306"